---
- name: despliegue aplicación next.js con secretos aws - app-secop
  hosts: produccion
  become: yes
  vars:
    secret_arn: "arn:aws:secretsmanager:us-east-1:290059794118:secret:prod-secop-uGe1Bk"
    project_path: "/opt/secop-licitaciones-datatable"
    repo_url: "https://github.com/Hmarquezrada/automated-deployment-with-ansible-iac-devops.git"

  tasks:
    - name: instalar dependencias necesarias
      apt:
        name:
          - git
          - jq
          - docker.io
          - docker-compose
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: detectar rama principal del repositorio
      shell: |
        git ls-remote --symref {{ repo_url }} HEAD | grep 'ref:' | awk '{print $2}' | sed 's/refs\/heads\///'
      register: branch_name
      changed_when: false

    - name: crear carpeta del proyecto
      file:
        path: "{{ project_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: clonar o actualizar repositorio
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: "{{ branch_name.stdout }}"
        force: yes

    - name: obtener secreto desde aws secrets manager
      command: >
        aws secretsmanager get-secret-value
        --secret-id {{ secret_arn }}
        --query SecretString
        --output text
      register: secreto_json

    - name: convertir secreto json a diccionario
      set_fact:
        secret_data: "{{ secreto_json.stdout | from_json }}"

    - name: generar archivo .env sin problemas de comillas
      copy:
        dest: "{{ project_path }}/.env"
        content: |
          {% for k, v in secret_data.items() %}
          {{ k }}={{ v }}
          {% endfor %}

    - name: mostrar variables .env obtenidas
      shell: cat {{ project_path }}/.env
      register: env_content

    - debug:
        msg: "{{ env_content.stdout_lines }}"

    - name: construir y levantar contenedor
      shell: |
        cd {{ project_path }}
        docker-compose build --no-cache
        docker-compose up -d
      args:
        executable: /bin/bash
